src/eAuto.Web/Areas/Customer/Controllers/CallRequestController.cs
using eAuto.Data.Interfaces;
using eAuto.Data.Interfaces.DataModels;
using eAuto.Web.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace eAuto.Web.Areas.Customer.Controllers
{
	[Area("Customer")]
	public class CallRequestController : Controller
	{
		private readonly IAppLogger<CallRequestController> _logger;
        private readonly IRepository<OrderCarDataModel> _orderCarRepository;
        private readonly UserManager<ApplicationUser> _userRepository;

        

		public CallRequestController(
            IRepository<OrderCarDataModel> orderCarRepository,
            IAppLogger<CallRequestController> logger,
            UserManager<ApplicationUser> userRepository)
		{
			_orderCarRepository = orderCarRepository;
			_userRepository = userRepository;
			_logger = logger;
		}

		[HttpGet]
		public IActionResult Index(int id)
		{
            OrderCarViewModel orderCarView = new();
			return View(orderCarView);
		}

		[HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(OrderCarViewModel orderCarView)
		{
            if (ModelState.IsValid)
			{
                var orderCallToDb = new OrderCarDataModel()
                {
                    OrderDate = DateTime.UtcNow,
                    OrderStatus = WebConstants.StatusPending,
                    Message = orderCarView.Message,
                    PhoneNumber = orderCarView.PhoneNumber,
                    Name = orderCarView.Name
                };
                var claimIdentity = (ClaimsIdentity)User.Identity!;
                var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
                if (claim != null)
                {
                    orderCallToDb.ApplicationUserId = _userRepository.GetUserId(User);
                }
                else
                {
                    orderCallToDb.ApplicationUserId = orderCarView.Name + Guid.NewGuid().ToString();
                }
                _orderCarRepository.Create(orderCallToDb);
            }
			
			return RedirectToAction("Index", "CarsCatalog");
		}
    }
}

src/eAuto.Web/Areas/Customer/Views/CallRequest/Index.cshtml
@model OrderCarViewModel

<form method="post" asp-controller="CallRequest" asp-action="Index" style="margin-top:3rem">
    <div class="row">
        <div class="col-md-4" style="margin:auto">
            <div>
                <h1>Call me back</h1>
            </div>
            <div>
                <div class="mb-3">
                    <label asp-for="@Model!.Name">Your Name: @Model.Name</label>
                    <input asp-for="@Model!.Name" class="form-control">
                    <span asp-validation-for="@Model!.Name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="@Model!.PhoneNumber">Your Phone: @Model.PhoneNumber</label>
                    <input asp-for="@Model!.PhoneNumber" type="text" class="form-control">
                    <span asp-validation-for="@Model!.PhoneNumber" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="@Model!.Message">Your Message: @Model.Message</label>
                    <textarea asp-for="@Model!.Message" class="form-control"></textarea>
                    <span asp-validation-for="@Model!.PhoneNumber" class="text-danger"></span>
                </div>
            </div>
            <div>
                <a asp-area="Customer" asp-controller="CarsCatalog" asp-action="Index" class="btn btn-secondary">Back to Catalog</a>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}