src/eAuto.Web/Models/BodyTypeViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace eAuto.Web.Models
{
	public sealed class BodyTypeViewModel
	{
		public int BodyTypeId { get; set; }
		[DisplayName("Body Type")]
		[Required]public string? Name { get; set; }
		public BodyTypeViewModel()
		{
		}

		public BodyTypeViewModel(int bodyTypeId, string name)
		{
			BodyTypeId = bodyTypeId;
			Name = name;
		}
	}
}

src/eAuto.Web/Areas/Admin/Controllers/BodyTypeController.cs
using eAuto.Data.Interfaces;
using eAuto.Domain.Interfaces;
using eAuto.Domain.Interfaces.Exceptions;
using eAuto.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace eAuto.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = WebConstants.AdminRole)]
    public class BodyTypeController : Controller
    {
        private readonly IAppLogger<BodyTypeController> _logger;
        private readonly IBodyTypeService _bodyTypeService;

        public BodyTypeController(IBodyTypeService bodyTypeService ,IAppLogger<BodyTypeController> logger)
        {
            _logger = logger;
            _bodyTypeService = bodyTypeService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
			try
			{
				var result = await _bodyTypeService.GetBodyTypeModelsAsync();
                var orderedResult = result
                    .Select(i => new BodyTypeViewModel
                {
                    BodyTypeId = i.BodyTypeId,
                    Name = i.Name!
                })
                    .OrderBy(i => i.Name);
				return View(orderedResult);
			}
			catch (GenericNotFoundException<BodyTypeController> ex)
			{
				_logger.LogError(ex, ex.Message);
				return NotFound(ex.Message);
			}
			catch(Exception ex)
			{
				_logger.LogError(ex, ex.Message); 
                return BadRequest(ex.Message);
			}
            
        }

		#region Create

		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
        [ValidateAntiForgeryToken]
		public IActionResult Create(BodyTypeViewModel viewModel)
		{
			IBodyType bodyType;
			try
			{
                if (ModelState.IsValid)
                {
                    bodyType = _bodyTypeService.CreateBodyTypeModel(viewModel.Name!);
                    bodyType.Save();
                    TempData["Success"] = "Body Type created successfully";
                    return RedirectToAction("Index");
                }
                return View(viewModel);
            }
			catch (GenericNotFoundException<BodyTypeController> ex)
			{
				_logger.LogError(ex, ex.Message);
				return RedirectToAction("Index");
			}
        }
        #endregion

        #region Edit

        [HttpGet]
        public IActionResult Edit(int id)
        {
            try
            {
                var viewModel = _bodyTypeService.GetBodyTypeModel(id);

                var bodyTypeViewModel = new BodyTypeViewModel
                {
                    BodyTypeId = id,
                    Name = viewModel.Name!
                };
                return View(bodyTypeViewModel);
            }

            catch (GenericNotFoundException<BodyTypeController> ex)
            {
				_logger.LogError(ex, ex.Message);
				return NotFound(ex.Message);
            }

            catch (Exception ex)
            {
				_logger.LogError(ex, ex.Message);
				return BadRequest(ex.Message);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(BodyTypeViewModel viewModel)
        {
            IBodyType bodyType;
            try
            {
                if (ModelState.IsValid)
                {
                    bodyType = _bodyTypeService.GetBodyTypeModel(viewModel.BodyTypeId);
                    bodyType.Name = viewModel.Name;
                    bodyType.Save();
                    TempData["Success"] = "Body Type edited successfully";
                    return RedirectToAction("Index");
                }
                return View(viewModel);
            }
            catch (GenericNotFoundException<BodyTypeController> ex )
            {
				_logger.LogError(ex, ex.Message);
				return RedirectToAction("Index");
            }
        }
        #endregion

        #region Delete
        public IActionResult Delete(int id)
        {
            try
            {
                var bodyType = _bodyTypeService.GetBodyTypeModel(id);
                bodyType.Delete();
                TempData["Success"] = "Body Type deleted successfully";
                return RedirectToAction("Index");
            }

            catch (GenericNotFoundException<BodyTypeController> ex)
            {
				_logger.LogError(ex, ex.Message);
				return NotFound(ex.Message);
            }

            catch (Exception ex)
            {
				_logger.LogError(ex, ex.Message);
				return BadRequest(ex.Message);
            }
            #endregion
        }
    }
}

src/eAuto.Web/Controllers/BodyTypeController.cs
using eAuto.Domain.Interfaces;
using eAuto.Domain.Interfaces.Exceptions;
using eAuto.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace eAuto.Web.Controllers
{
    public class BodyTypeController : Controller
    {
        private readonly ILogger<BodyTypeController> _logger;
        private readonly IBodyTypeService _bodyTypeService;

        public BodyTypeController(IBodyTypeService bodyTypeService ,ILogger<BodyTypeController> logger)
        {
            _logger = logger;
            _bodyTypeService = bodyTypeService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
			try
			{
				var result = await _bodyTypeService.GetBodyTypeModelsAsync();
				return View(result);
			}
			catch (BodyTypeNotFoundException ex)
			{
				//TODO logger
				return NotFound(ex.Message);
			}
			catch(Exception ex)
			{
				//TODO logger
				return BadRequest(ex.Message);
			}
            
        }

		#region Create

		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
        [ValidateAntiForgeryToken]
		public IActionResult Create(BodyTypeViewModel viewModel)
		{
			IBodyType bodyType;
			try
			{
                if (ModelState.IsValid)
                {
                    bodyType = _bodyTypeService.CreateBodyTypeModel(viewModel.Name);
                    bodyType.Save();
                    TempData["Success"] = "Body Type created successfully";
                    return RedirectToAction("Index");
                }
                return View(viewModel);
            }
			catch (BodyTypeNotFoundException)
			{
				return RedirectToAction("Index");
			}
        }
        #endregion

        #region Edit

        [HttpGet]
        public IActionResult Edit(int id)
        {
            try
            {
                var viewModel = _bodyTypeService.GetBodyTypeModel(id);

                var bodyTypeViewModel = new BodyTypeViewModel
                {
                    BodyTypeId = id,
                    Name = viewModel.Name
                };
                return View(bodyTypeViewModel);
            }

            catch (BodyTypeNotFoundException ex)
            {
                _logger!.LogError(ex.Message);
                return NotFound(ex.Message);
            }

            catch (Exception ex)
            {
                _logger!.LogError(ex.Message);
                return BadRequest(ex.Message);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(BodyTypeViewModel viewModel)
        {
            IBodyType bodyType;
            try
            {
                if (ModelState.IsValid)
                {
                    bodyType = _bodyTypeService.GetBodyTypeModel(viewModel.BodyTypeId);
                    bodyType.Name = viewModel.Name;
                    bodyType.Save();
                    TempData["Success"] = "Body Type edited successfully";
                    return RedirectToAction("Index");
                }
                return View(viewModel);
            }
            catch (BodyTypeNotFoundException)
            {
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region Delete
        public IActionResult Delete(int id)
        {
            try
            {
                var bodyType = _bodyTypeService.GetBodyTypeModel(id);
                bodyType.Delete();
                TempData["Success"] = "Body Type deleted successfully";
                return RedirectToAction("Index");
            }

            catch (BodyTypeNotFoundException ex)
            {
                _logger!.LogError(ex.Message);
                return NotFound(ex.Message);
            }

            catch (Exception ex)
            {
                _logger!.LogError(ex.Message);
                return BadRequest(ex.Message);
            }
            #endregion
        }
    }
}

src/eAuto.Web/Areas/Admin/Views/BodyType/Create.cshtml
@model BodyTypeViewModel

<form method="post" asp-controller="BodyType" asp-action="Create">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h3 class="text-black-50">Create new Body Type</h3>
		</div>
		<div class="mb-3">
			<label asp-for="@Model.Name"></label>
			<input asp-for="@Model.Name" class="form-control">
			<span asp-validation-for="@Model.Name" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-success btn-sm" style="width:100px">
			<i class="bi bi-check-lg"></i>
			Create
		</button>
		<a asp-controller="BodyType" asp-action="index" class="btn btn-primary btn-sm" style="width:100px">
			<span class="bi bi-reply"> Back</span>
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

src/eAuto.Web/Areas/Admin/Views/BodyType/Edit.cshtml
@model BodyTypeViewModel

<form method="post" asp-controller="BodyType" asp-action="Edit"> 

	<input asp-for="@Model.BodyTypeId" hidden />

	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-black-50">Edit</h2>
		</div>
		<div class="mb-3">
			<label asp-for="@Model.Name"></label>
			<input asp-for="@Model.Name" class="form-control">
			<span asp-validation-for="@Model.Name" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-success btn-sm" style="width:100px">
			<i class="bi bi-check-lg"></i>
			Update
		</button>
		<a asp-controller="BodyType" asp-action="index" class="btn btn-primary btn-sm" style="width:100px">
			<span class="bi bi-reply"> Back</span>
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

src/eAuto.Web/Areas/Admin/Views/BodyType/Index.cshtml
@model IEnumerable<BodyTypeViewModel>

<partial name="_Notification" />
<div class="container p-3" />
<div class="row pt-4">
    <div class="col-6">
        <h2 class="text-primary text-black-50">Body Types</h2>
    </div>
    <div class="col-6 text-end">
        <a asp-controller="BodyType" asp-action="Create" class="btn btn-outline-success">
            <i class="bi bi-pen">Add</i>
        </a>
    </div>
</div>


@if (Model.Count() == 0)
{
    <table class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Body Type
                </th>
            </tr>
        </thead>
    </table>
}
else
{
    <table class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Body Type</th>
                <th width="110px">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="95%">
                        @obj.Name
                    </td>
                    <td width="10%" align="center">
                        <div class="btn-toolbar justify-content-between" role="toolbar" style="width:6rem">
                            <a asp-controller="BodyType" asp-action="Edit" asp-route-id="@obj.BodyTypeId" class="btn btn-outline-primary">
                                <i class="bi bi-wrench"></i>
                            </a>

                            <form method="post" asp-controller="BodyType" asp-action="Delete" asp-route-id="@obj.BodyTypeId">
                                <button type="submit" class="btn btn-outline-danger">
                                    <i class="bi bi-trash3"></i>
                                </button>
                            </form>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}