src/eAuto.Web/Areas/Customer/Controllers/CarsCatalogController.cs
using eAuto.Data.Interfaces;
using eAuto.Domain.Interfaces;
using eAuto.Domain.Interfaces.Exceptions;
using eAuto.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;

namespace eAuto.Web.Areas.Customer.Controllers
{
	[Area("Customer")]
	public class CarsCatalogController : Controller
	{
		private readonly IAppLogger<CarsCatalogController> _logger;

		private readonly ICarService _carService;
		private readonly IBrandService _brandService;
		private readonly IModelService _modelService;
		private readonly IGenerationService _generationService;
		private readonly IBodyTypeService _bodyTypeService;
		private readonly IDriveTypeService _driveTypeService;
		private readonly ITransmissionService _transmissionService;
		private readonly IEngineTypeService _engineTypeService;

		public CarsCatalogController(
			ICarService carService,
			IBrandService brandService,
			IModelService modelService,
			IGenerationService generationService,
			IBodyTypeService bodyTypeService,
			IDriveTypeService driveTypeService,
			ITransmissionService transmissionService,
			IEngineTypeService engineTypeService,
			IAppLogger<CarsCatalogController> logger)
		{
			_carService = carService;
			_brandService = brandService;
			_modelService = modelService;
			_generationService = generationService;
			_bodyTypeService = bodyTypeService;
			_driveTypeService = driveTypeService;
			_transmissionService = transmissionService;
			_engineTypeService = engineTypeService;
			_logger = logger;
		}

		[HttpGet]
		public async Task<IActionResult> Index(CarsIndexViewModel carsIndex, int? pageId)
		{
			try
			{
				var iCarsList = await _carService.GetCarModelsAsync();
				var carsList = iCarsList
					.Select(i => new CarViewModel
					{
						CarId = i.CarId,
						PriceInitial = i.PriceInitial,
						PictureUrl = i.PictureUrl,
						Year = i.Year,
						DateArrival = i.DateArrival,
						Odometer = i.Odometer,
						Description = i!.Description!,
						BrandId = i.BrandId,
						EngineIdentificationName = i.EngineIdentificationName,
						EngineCapacity = i.EngineCapacity,
						EngineFuelType = i.EngineFuelType,
						EngineFuelTypeId = i.EngineFuelTypeId,
						EnginePower = i.EnginePower,
						Brand = i.Brand,
						ModelId = i.ModelId,
						Model = i.Model,
						GenerationId = i.GenerationId,
						Generation = i.Generation,
						BodyTypeId = i.BodyTypeId,
						BodyType = i.BodyType,
						DriveTypeId = i.DriveTypeId,
						DriveType = i.DriveType,
						TransmissionId = i.TransmissionId,
						Transmission = i.Transmission
					});
				var carsQuery = carsList
					.Where(i => (!carsIndex.BrandFilterApplied.HasValue || i.BrandId == carsIndex.BrandFilterApplied)
								&& (!carsIndex.ModelFilterApplied.HasValue || i.ModelId == carsIndex.ModelFilterApplied)
								&& (!carsIndex.GenerationFilterApplied.HasValue || i.GenerationId == carsIndex.GenerationFilterApplied)
								&& (!carsIndex.BodyTypeFilterApplied.HasValue || i.BodyTypeId == carsIndex.BodyTypeFilterApplied)
								&& (!carsIndex.DriveTypeFilterApplied.HasValue || i.DriveTypeId == carsIndex.DriveTypeFilterApplied)
								&& (!carsIndex.TransmissionFilterApplied.HasValue || i.TransmissionId == carsIndex.TransmissionFilterApplied)
								&& (!carsIndex.EngineTypeFilterApplied.HasValue || i.EngineFuelTypeId == carsIndex.EngineTypeFilterApplied))
					.Select(i =>
						new CarViewModel(
							i.CarId,
							i.PriceInitial,
							i.PictureUrl!,
							i.Year,
							i.DateArrival,
							i.Odometer,
							i.Description!,
							i.EngineIdentificationName,
							i.EngineCapacity,
							i.EngineFuelType!,
							i.EngineFuelTypeId,
							i.EnginePower,
							i.Brand!,
							i.Model!,
							i.Generation!,
							i.BodyType!,
							i.DriveType!,
							i.Transmission!
					)).ToList();

				var carsResult = new CarsIndexViewModel()
				{
					CarVModels = carsQuery,
					Brands = new List<SelectListItem>(),
					Models = new List<SelectListItem>(),
					Generations = new List<SelectListItem>(),
					BodyTypes = new List<SelectListItem>(),
					DriveTypes = new List<SelectListItem>(),
					Transmissions = new List<SelectListItem>(),
					EngineTypes = new List<SelectListItem>()

				};

				return View(carsResult);
			}
			catch (GenericNotFoundException<CarsCatalogController> ex)
			{
				_logger.LogError(ex, ex.Message);
				return NotFound(ex.Message);
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, ex.Message);
				return BadRequest(ex.Message);
			}

		}

		public IActionResult Details(int id)
		{
			var queryCar = _carService.GetCarModel(id);

			var result = new CarViewModel(
                    id,
                    queryCar.PriceInitial,
                    queryCar.PictureUrl!,
                    queryCar.Year,
                    queryCar.DateArrival,
                    queryCar.Odometer,
                    queryCar.Description!,
                    queryCar.EngineIdentificationName!,
                    queryCar.EngineCapacity,
                    queryCar.EngineFuelType!,
                    queryCar.EngineFuelTypeId,
                    queryCar.EnginePower,
                    queryCar.Brand!,
                    queryCar.Model!,
                    queryCar.Generation!,
                    queryCar.BodyType!,
                    queryCar.DriveType!,
                    queryCar.Transmission!);
       
			return View(result);
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}

		#region API
		[HttpGet]
		public async Task<ActionResult> GetBrands()
		{
			var brands = await _brandService.GetBrandModelsAsync();
			var query = brands
				.OrderBy(m => m.Name)
				.Select(m => new SelectListItem
				{
					Value = m.BrandId.ToString(),
					Text = m.Name
				});
			return Json(query);
		}

		[HttpGet]
		public async Task<ActionResult> GetBodyTypes()
		{
			var bodyTypes = await _bodyTypeService.GetBodyTypeModelsAsync();
			var query = bodyTypes
				.OrderBy(m => m.Name)
				.Select(m => new SelectListItem
				{
					Value = m.BodyTypeId.ToString(),
					Text = m.Name
				});
			return Json(query);
		}

		[HttpGet]
		public async Task<ActionResult> GetDriveTypes()
		{
			var driveTypes = await _driveTypeService.GetDriveTypeModelsAsync();
			var query = driveTypes
				.OrderBy(m => m.Name)
				.Select(m => new SelectListItem
				{
					Value = m.DriveTypeId.ToString(),
					Text = m.Name
				});
			return Json(query);
		}

		[HttpGet]
		public async Task<ActionResult> GetTransmissions()
		{
			var transmissions = await _transmissionService.GetTransmissionModelsAsync();
			var query = transmissions
				.OrderBy(m => m.Name)
				.Select(m => new SelectListItem
				{
					Value = m.TransmissionId.ToString(),
					Text = m.Name
				});
			return Json(query);
		}

		[HttpGet]
		public async Task<ActionResult> GetEngineTypes()
		{
			var engineTypes = await _engineTypeService.GetEngineTypesAsync();
			var query = engineTypes
				.OrderBy(m => m.Name)
				.Select(m => new SelectListItem
				{
					Value = m.EngineTypeId.ToString(),
					Text = m.Name
				});
			return Json(query);
		}

		[HttpGet]
		public async Task<ActionResult> GetModels(int BrandFilterApplied)
		{
			var modelsSel = await _modelService.GetModelModelsAsync();
			var query = modelsSel
				.Where(m => m.BrandId == BrandFilterApplied)
				.OrderBy(m => m.Name)
				.Select(m => new SelectListItem
				{
					Value = m.ModelId.ToString(),
					Text = m.Name
				});
			return Json(query);
		}

		[HttpGet]
		public async Task<ActionResult> GetGenerations(int ModelFilterApplied)
		{
			var generationsSel = await _generationService.GetGenerationModelsAsync();
			var query = generationsSel
				.Where(m => m.ModelId == ModelFilterApplied)
				.OrderBy(m => m.Name)
				.Select(m => new SelectListItem
				{
					Value = m.GenerationId.ToString(),
					Text = m.Name
				});
			return Json(query);
		}
		#endregion
	}
}

src/eAuto.Web/Areas/Customer/Views/CarsCatalog/Details.cshtml
@model CarViewModel

<form method="post" class="pt-4">
    <input asp-for="@Model.CarId" hidden />

    <div class="card container" style="border: solid 1px; margin:auto">
        <div class="card-header bg-dark text-light ml-0 row" style="padding:2rem">
            <div class="col-12 col-md-6">
                <h1 class="text-white">@Model.Brand | @Model.Model</h1>
                <p class="text-white">@Model.Generation</p>
            </div>
            <div class="col-12 col-md-6 text-end pt-4">
                <span class="badge bg-light pt-2" style="height:30px;">@Model.Year.Year.ToString()</span>
                <span class="badge bg-warning pt-2" style="height:30px;">@Model.DriveType</span>
            </div>
        </div>
        <div class="card-body row container" style="justify-content: center">
            <div class="row" style="margin-top: 2rem">
                <div class="col-lg-6">
                    <img src="@Model.PictureUrl" width="100%" class="rounded" />
                </div>
                <div class="col-lg-6" style="text-align: center; margin-top:1rem">
                    <h5 class="text-primary pb-2">Brand: <span>@Model.Brand</span></h5>
                    <h5 class="text-primary pb-2">Model: <span>@Model.Model</span></h5>
                    <h5 class="text-primary pb-2">Generation: <span>@Model.Generation</span></h5>
                    <h5 class="text-primary pb-2">Year: <span>@Model.Year.Year.ToString()</span></h5>
                    <h5 class="text-primary pb-2">Bodytype: <span>@Model.BodyType</span></h5>
                    <h5 class="text-primary pb-2">Date of arrival: <span>@Model.DateArrival.ToString("MM.yyyy")</span></h5>
                    <h5 class="text-primary pb-2">Capacity: <span>@Model.EngineFuelType</span> | <span>@Model.EngineCapacity</span></h5>
                    <h5 class="text-primary pb-2">Odometer: <span>@Model.Odometer</span></h5>
                    <h5 class="text-primary pb-2">Transmission: <span>@Model.Transmission</span></h5>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <p class="text-secondary mt-5">@Html.Raw(Model.Description)</p>
                    <h3 class="text-primary pb-2 mt-5">Price: @Model.PriceInitial.ToString("c", WebConstants.CultureInfoEN_US)</h3>
                </div>
            </div>
        </div>
        <div>
            <div class="row" style="margin: 2rem">
                <hr/>
                <div class="col-md-6 pb-1">
                    <a class="btn btn-outline-dark form-control " style="height:50px; border:none" asp-action="Index">Back to Catalog</a>
                </div>
                <div class="col-md-6 pb-1">
                    <a asp-area="Customer" asp-controller="CallRequest" asp-action="Index" asp-route-id="@Model.CarId" class="btn btn-success form-control" style="height:50px;">Order Now</a>
                </div>
            </div>
        </div>
    </div>
</form>

src/eAuto.Web/Areas/Customer/Views/CarsCatalog/Index.cshtml
@model CarsIndexViewModel

<div>
	<div class="container mt-5">
		<form method="get">
			<div class="row home">
				<div class="col-lg-3">
					<label asp-for="Brands" class="control-label" style="font"></label>
					<select id="1stBrand" asp-for="BrandFilterApplied" asp-items="@Model.Brands" class="form-select" style="background-color:#fff"></select>
				</div>
				<div class="col-lg-3">
					<label asp-for="Models" class="control-label"></label>
					<select id="1stModel" asp-for="ModelFilterApplied" asp-items="@Model.Models" class="form-select" style="background-color:#fff"></select>
				</div>
				<div class="col-lg-3">
					<label asp-for="Generations" class="control-label"></label>
					<select id="1stGeneration" asp-for="GenerationFilterApplied" asp-items="@Model.Generations" class="form-select" style="background-color:#fff">	</select>
				</div>
				<div class="col-lg-3">
					<label asp-for="BodyTypes" class="control-label"></label>
					<select id="1stBodyType" asp-for="@Model.BodyTypeFilterApplied" asp-items="@Model.BodyTypes" class="form-select" style="background-color:#fff"></select>
				</div>
			</div>
			<div class="row home mt-2">
				<div class="col-lg-3">
					<label asp-for="DriveTypes" class="control-label"></label>
					<select id="1stDriveType" asp-for="@Model.DriveTypeFilterApplied" asp-items="@Model.DriveTypes" class="form-select" style="background-color:#fff"></select>
				</div>
				<div class="col-lg-3">
					<label asp-for="Transmissions" class="control-label"></label>
					<select id="1stTransmission" asp-for="@Model.TransmissionFilterApplied" asp-items="@Model.Transmissions" class="form-select" style="background-color:#fff"></select>
				</div>
				<div class="col-lg-3">
					<label asp-for="EngineTypes" class="control-label"></label>
					<select id="1stEngineType" asp-for="@Model.EngineTypeFilterApplied" asp-items="@Model.EngineTypes" class="form-select" style="background-color:#fff"></select>
				</div>
				<div class="col-lg-3 mt-4" style="text-align:center">
					<button type="submit" class="btn btn-outline-dark" style="width:14rem">
						Apply
					</button>
				</div>
			</div>
		</form>
	</div>
</div>
<div style="width:90%; margin: auto">
	<div class="row pb-3">
		@foreach (var product in Model.CarVModels!)
		{
			<div class="col-lg-3 col-md-6 mt-5">
				<div class="row p-2">
					<div class="col-12 p-1">
						<div class="card" style="border: solid #343a40 1px;border-radius: unset">
							<a asp-controller="CarsCatalog" asp-action="Details" asp-route-id="@product.CarId">
								<img src=@product.PictureUrl class="card-img-top" style="border-radius:unset" />
							</a>
							<div class="card-body">
								<div class="pl-1">
									<p class="card-title h5 text-primary" style="height:3rem">@product.Brand | @product.Model </p>
									<p class="card-title text-secondary"><b>@product.Generation</b></p>
									<p class="card-title text-primary"><b>@product.Year.Year.ToString()</b></p>
									<p class="card-title text-muted"><b>@product.EngineFuelType | @product.EngineCapacity</b></p>
								</div>
								<div class="pl-1">
									<p>Price: <b><span class="text-success"></span>@product.PriceInitial.ToString("C", WebConstants.CultureInfoEN_US)</b></p>
								</div>
							</div>
						</div>
						<div style="margin-top: 1rem">
							<a asp-action="Details" type="button" class="btn btn-outline-dark form-control" asp-route-id="@product.CarId">
								Details
							</a>
						</div>
					</div>
				</div>
			</div>
		}
	</div>
</div>



@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}

	<script type="text/javascript">
		$(document).ready(function (){
			var selectedBrand = $('#1stBrand');
			var selectedModel = $('#1stModel');
			var selectedGeneration = $('#1stGeneration');
			var selectedBodyType = $('#1stBodyType');
			var selectedDriveType = $('#1stDriveType');
			var selectedTransmission = $('#1stTransmission');
			var selectedEngineType = $('#1stEngineType');
			
			selectedBrand.append($('<option/>', {
				value: null,
				text: 'All Brands',
			}));

			selectedModel.append($('<option/>', {
				value: null,
				text: 'Select Brand',
			}));

			selectedGeneration.append($('<option/>', {
				value: null,
				text: 'Select Model',
			}));

			selectedBodyType.append($('<option/>', {
				value: null,
				text: 'All Body Types',
			}));

			selectedDriveType.append($('<option/>', {
				value: null,
				text: 'All Drive Types',
			}));

			selectedTransmission.append($('<option/>', {
				value: null,
				text: 'All Transmissions',
			}));

			selectedEngineType.append($('<option/>', {
				value: null,
				text: 'All Engine Types',
			}));

			$.getJSON('@Url.Action("GetBrands")', function (brands){
				if (brands != null && !jQuery.isEmptyObject(brands)) {
					$.each(brands, function (index, brand) {
						selectedBrand.append($('<option/>', {
							value: brand.value,
							text: brand.text,
						}));
					});
				};
			});

			$.getJSON('@Url.Action("GetBodyTypes")', function (bodyTypes) {
				if (bodyTypes != null && !jQuery.isEmptyObject(bodyTypes)) {
					$.each(bodyTypes, function (index, bodyType) {
						selectedBodyType.append($('<option/>', {
							value: bodyType.value,
							text: bodyType.text,
						}));
					});
				};
			});

			$.getJSON('@Url.Action("GetDriveTypes")', function (driveTypes) {
				if (driveTypes != null && !jQuery.isEmptyObject(driveTypes)) {
					$.each(driveTypes, function (index, driveType) {
						selectedDriveType.append($('<option/>', {
							value: driveType.value,
							text: driveType.text,
						}));
					});
				};
			});

			$.getJSON('@Url.Action("GetTransmissions")', function (transmissions) {
				if (transmissions != null && !jQuery.isEmptyObject(transmissions)) {
					$.each(transmissions, function (index, transmission) {
						selectedTransmission.append($('<option/>', {
							value: transmission.value,
							text: transmission.text,
						}));
					});
				};
			});

			$.getJSON('@Url.Action("GetEngineTypes")', function (engineTypes) {
				if (engineTypes != null && !jQuery.isEmptyObject(engineTypes)) {
					$.each(engineTypes, function (index, engineType) {
						selectedEngineType.append($('<option/>', {
							value: engineType.value,
							text: engineType.text,
						}));
					});
				};
			});
		});
	</script>

	<script type="text/javascript">
		$(document).ready(function () {
			$('#1stBrand').change(function () {
				var selectedBrand = $('#1stBrand').val();
				var modelSelect = $('#1stModel');
				modelSelect.empty();

				if (selectedBrand != null && selectedBrand != '') {
					$.getJSON('@Url.Action("GetModels")', { BrandFilterApplied: selectedBrand }, function (models) {
						if (models != null && !jQuery.isEmptyObject(models)) {
							modelSelect.append($('<option/>', {
								value: null,
								text: "Select Model"
							}));
							$.each(models, function (index, model) {
								modelSelect.append($('<option/>', {
									value: model.value,
									text: model.text,
								}));
							});
						} else {
							modelSelect.append($('<option/>', {
								value: null,
								text: "Select Model"
							}));
						};
					});
				};
			});
		});
	</script>

	<script type="text/javascript">
		$(document).ready(function () {

			$('#1stBrand').change(function () {
				var selectedBrand = $('#1stBrand').val();
				var generationSelect = $('#1stGeneration');
				generationSelect.empty();

				if (selectedBrand != null && selectedBrand != '') {
					generationSelect.append($('<option/>', {
						value: null,
						text: "Select Generation"
					}));
				};
			});

			$('#1stModel').change(function () {
				var selectedModel = $('#1stModel').val();
				var generationSelect = $('#1stGeneration');
				generationSelect.empty();

				if (selectedModel != null && selectedModel != '') {
					$.getJSON('@Url.Action("GetGenerations")', { ModelFilterApplied: selectedModel }, function (generations) {
						if (generations != null && !jQuery.isEmptyObject(generations)) {
							generationSelect.append($('<option/>', {
								value: null,
								text: "Select Generation"
							}));
							$.each(generations, function (index, generation) {
								generationSelect.append($('<option/>', {
									value: generation.value,
									text: generation.text,
								}));
							});
						} else {
							generationSelect.append($('<option/>', {
								value: null,
								text: "Select Generation"
							}));
						};
					});
				};
			});
		});
	</script>
}