src/eAuto.Web/Models/DriveTypeViewModel.cs
using System.ComponentModel;

namespace eAuto.Web.Models
{
	public sealed class DriveTypeViewModel
    {
		public int DriveTypeId { get; set; }
		[DisplayName("Drive Type")]
		public string? Name { get; set; }
		public DriveTypeViewModel()
		{
		}

		public DriveTypeViewModel(int driveTypeId, string name)
		{
            DriveTypeId = driveTypeId;
			Name = name;
		}
	}
}

src/eAuto.Web/Areas/Admin/Controllers/DriveTypeController.cs
using eAuto.Data.Interfaces;
using eAuto.Domain.Interfaces;
using eAuto.Domain.Interfaces.Exceptions;
using eAuto.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace eAuto.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = WebConstants.AdminRole)]
    public class DriveTypeController : Controller
    {
        private readonly IAppLogger<DriveTypeController> _logger;
        private readonly IDriveTypeService _driveTypeService;

        public DriveTypeController(
            IDriveTypeService driveTypeService ,IAppLogger<DriveTypeController> logger)
        {
            _logger = logger;
            _driveTypeService = driveTypeService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
			try
			{
				var driveTypes = await _driveTypeService.GetDriveTypeModelsAsync();
                var viewModelList = driveTypes
                    .Select(i => new DriveTypeViewModel
                    {
                        DriveTypeId = i.DriveTypeId,
                        Name = i.Name
                    })
                    .OrderBy(i => i.Name);
				return View(viewModelList);
			}
			catch (GenericNotFoundException<DriveTypeController> ex)
			{
				_logger.LogError(ex, ex.Message);
				return NotFound(ex.Message);
			}
			catch(Exception ex)
			{
				_logger.LogError(ex, ex.Message);
				return BadRequest(ex.Message);
			}
            
        }

		#region Create

		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
        [ValidateAntiForgeryToken]
		public IActionResult Create(DriveTypeViewModel viewModel)
		{
			IDriveType driveType;
			try
			{
                if (ModelState.IsValid)
                {
                    driveType = _driveTypeService.CreateDriveTypeDomainModel();

                    driveType.DriveTypeId = viewModel.DriveTypeId;
                    driveType.Name = viewModel.Name;

                    driveType.Save();
                    TempData["Success"] = "Drive Type created successfully";
                    return RedirectToAction("Index");
                }
                return View(viewModel);
            }
			catch (GenericNotFoundException<DriveTypeController> ex)
			{
				_logger.LogError(ex, ex.Message);
				return RedirectToAction("Index");
			}
        }
        #endregion

        #region Edit

        [HttpGet]
        public IActionResult Edit(int id)
        {
            try
            {
                var viewModel = _driveTypeService.GetDriveTypeModel(id);

                var driveTypeViewModel = new DriveTypeViewModel
                {
                    DriveTypeId = id,
                    Name = viewModel.Name
                };
                return View(driveTypeViewModel);
            }

            catch (GenericNotFoundException<DriveTypeController> ex)
            {
				_logger.LogError(ex, ex.Message);
				return NotFound(ex.Message);
            }

            catch (Exception ex)
            {
				_logger.LogError(ex, ex.Message);
				return BadRequest(ex.Message);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(DriveTypeViewModel viewModel)
        {
            IDriveType driveType;
            try
            {
                if (ModelState.IsValid)
                {
                    driveType = _driveTypeService.GetDriveTypeModel(viewModel.DriveTypeId);
                    driveType.Name = viewModel.Name;
                    driveType.Save();
                    TempData["Success"] = "Drive Type edited successfully";
                    return RedirectToAction("Index");
                }
                return View(viewModel);
            }
            catch (GenericNotFoundException<DriveTypeController> ex)
            {
				_logger.LogError(ex, ex.Message);
				return RedirectToAction("Index");
            }
        }
        #endregion

        #region Delete
        public IActionResult Delete(int id)
        {
            try
            {
                var driveType = _driveTypeService.GetDriveTypeModel(id);
                driveType.Delete();
                TempData["Success"] = "Drive Type deleted successfully";
                return RedirectToAction("Index");
            }

            catch (GenericNotFoundException<DriveTypeController> ex)
            {
				_logger.LogError(ex, ex.Message);
				return NotFound(ex.Message);
            }

            catch (Exception ex)
            {
				_logger.LogError(ex, ex.Message);
				return BadRequest(ex.Message);
            }
            #endregion
        }
    }
}

src/eAuto.Web/Controllers/DriveTypeController.cs
using eAuto.Domain.Interfaces;
using eAuto.Domain.Interfaces.Exceptions;
using eAuto.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace eAuto.Web.Controllers
{
    public class DriveTypeController : Controller
    {
        private readonly ILogger<DriveTypeController> _logger;
        private readonly IDriveTypeService _driveTypeService;

        public DriveTypeController(IDriveTypeService driveTypeService ,ILogger<DriveTypeController> logger)
        {
            _logger = logger;
            _driveTypeService = driveTypeService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
			try
			{
				var driveTypes = await _driveTypeService.GetDriveTypeModelsAsync();
                var viewModelList = driveTypes
                    .Select(i => new DriveTypeViewModel
                    {
                        DriveTypeId = i.DriveTypeId,
                        Name = i.Name
                    });
				return View(viewModelList);
			}
			catch (DriveTypeNotFoundException ex)
			{
				//TODO logger
				return NotFound(ex.Message);
			}
			catch(Exception ex)
			{
				//TODO logger
				return BadRequest(ex.Message);
			}
            
        }

		#region Create

		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
        [ValidateAntiForgeryToken]
		public IActionResult Create(DriveTypeViewModel viewModel)
		{
			IDriveType driveType;
			try
			{
                if (ModelState.IsValid)
                {
                    driveType = _driveTypeService.CreateDriveTypeDomainModel();

                    driveType.DriveTypeId = viewModel.DriveTypeId;
                    driveType.Name = viewModel.Name;

                    driveType.Save();
                    TempData["Success"] = "Drive Type created successfully";
                    return RedirectToAction("Index");
                }
                return View(viewModel);
            }
			catch (DriveTypeNotFoundException)
			{
				return RedirectToAction("Index");
			}
        }
        #endregion

        #region Edit

        [HttpGet]
        public IActionResult Edit(int id)
        {
            try
            {
                var viewModel = _driveTypeService.GetDriveTypeModel(id);

                var driveTypeViewModel = new DriveTypeViewModel
                {
                    DriveTypeId = id,
                    Name = viewModel.Name
                };
                return View(driveTypeViewModel);
            }

            catch (DriveTypeNotFoundException ex)
            {
                _logger!.LogError(ex.Message);
                return NotFound(ex.Message);
            }

            catch (Exception ex)
            {
                _logger!.LogError(ex.Message);
                return BadRequest(ex.Message);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(DriveTypeViewModel viewModel)
        {
            IDriveType driveType;
            try
            {
                if (ModelState.IsValid)
                {
                    driveType = _driveTypeService.GetDriveTypeModel(viewModel.DriveTypeId);
                    driveType.Name = viewModel.Name;
                    driveType.Save();
                    TempData["Success"] = "Drive Type edited successfully";
                    return RedirectToAction("Index");
                }
                return View(viewModel);
            }
            catch (DriveTypeNotFoundException)
            {
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region Delete
        public IActionResult Delete(int id)
        {
            try
            {
                var driveType = _driveTypeService.GetDriveTypeModel(id);
                driveType.Delete();
                TempData["Success"] = "Drive Type deleted successfully";
                return RedirectToAction("Index");
            }

            catch (DriveTypeNotFoundException ex)
            {
                _logger!.LogError(ex.Message);
                return NotFound(ex.Message);
            }

            catch (Exception ex)
            {
                _logger!.LogError(ex.Message);
                return BadRequest(ex.Message);
            }
            #endregion
        }
    }
}

src/eAuto.Web/Areas/Admin/Views/DriveType/Create.cshtml
@model DriveTypeViewModel

<form method="post" asp-controller="DriveType" asp-action="Create">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h3 class="text-black-50">Create new Drive Type</h3>
		</div>
		<div class="mb-3">
			<label asp-for="@Model.Name"></label>
			<input asp-for="@Model.Name" class="form-control">
			<span asp-validation-for="@Model.Name" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-success btn-sm" style="width:100px">
			<i class="bi bi-check-lg"></i>
			Create
		</button>
		<a asp-controller="Transmission" asp-action="index" class="btn btn-primary btn-sm" style="width:100px">
			<span class="bi bi-reply"> Back</span>
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

src/eAuto.Web/Areas/Admin/Views/DriveType/Edit.cshtml
@model DriveTypeViewModel

<form method="post" asp-controller="DriveType" asp-action="Edit">

	<input asp-for="@Model.DriveTypeId" hidden />

	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-black-50">Edit Drive Type</h2>
		</div>
		<div class="mb-3">
			<label asp-for="@Model.Name"></label>
			<input asp-for="@Model.Name" class="form-control">
			<span asp-validation-for="@Model.Name" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-success btn-sm" style="width:100px">
			<i class="bi bi-check-lg"></i>
			Update
		</button>
		<a asp-controller="DriveType" asp-action="index" class="btn btn-primary btn-sm" style="width:100px">
			<span class="bi bi-reply"> Back</span>
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

src/eAuto.Web/Areas/Admin/Views/DriveType/Index.cshtml
@model IEnumerable<DriveTypeViewModel>

<partial name="_Notification" />
<div class="container p-3" />
<div class="row pt-4">
    <div class="col-6">
        <h2 class="text-primary text-black-50">Drive Types</h2>
    </div>
    <div class="col-6 text-end">
        <a asp-controller="DriveType" asp-action="Create" class="btn btn-outline-success">
            <i class="bi bi-pen">Add</i>
        </a>
    </div>
</div>


@if (Model.Count() == 0)
{
    <table class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Drive Types
                </th>
            </tr>
        </thead>
    </table>
}
else
{
    <table class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Drive Type</th>
                <th width="110px">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="90%">
                        @obj.Name
                    </td>
                    <td width="10%" align="center">
                        <div class="btn-toolbar justify-content-between" role="toolbar" style="width:6rem">
                            <a asp-controller="DriveType" asp-action="Edit" asp-route-id="@obj.DriveTypeId" class="btn btn-outline-primary">
                                <i class="bi bi-wrench"></i>
                            </a>

                            <form method="post" asp-controller="DriveType" asp-action="Delete" asp-route-id="@obj.DriveTypeId">
                                <button type="submit" class="btn btn-outline-danger">
                                    <i class="bi bi-trash3"></i>
                                </button>
                            </form>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}